[MISC] Implemented 2021 Game State
pioneers/runtime pull request #184
Opened 2021-02-06 23:00 UTC by benliao1

Things that were specific to the 2021 game (`HYPOTHERMIA`, `POISON_IVY`, and `DEHYDRATION`) were implemented according to specifics from Shepherd and Atlas. There is a new file, `executor/filter.c`, which filters the commands to motors from student code according to the specification to create certain motor behaviors.

Changes were also made in `net_handler` and `shm_wrapper` to accomodate the new protobuf coming from Shepherd and to add additional robot state variables to keep track of these states.

Closes #182

2021-02-06 23:19 UTC, AVSurfer123 requested changes

2021-02-06 23:19 UTC, AVSurfer123 commented on tests/client/net_handler_client.c
> +    writen(nh_tcp_shep_fd, send_buf, len + BUFFER_OFFSET);
Need to check return status

2021-02-06 23:19 UTC, AVSurfer123 commented on executor/filter.c
> +#define KOALABEAR 6
Shouldn't do this cus hardcoding is bad, instead just call the function in the beginning of `gamestate_handler`

2021-02-06 23:19 UTC, AVSurfer123 commented on executor/filter.c
> +#define IDX_VELOCITY_B 8
Same for these. Instead use `get_param_idx`

2021-02-06 23:19 UTC, AVSurfer123 commented on executor/filter.c
> +#include "filter.h"
Can we rename both files to `gamestate_filter.*` because filter is not descriptive

2021-02-06 23:19 UTC, AVSurfer123 commented on executor/Makefile
> +executor: executor.c filter.c ../shm_wrapper/shm_wrapper.c ../logger/logger.c ../runtime_util/runtime_util.c ../net_handler/net_util.c ../net_handler/pbc_gen/text.pb-c.c
Rename this too

2021-02-06 23:45 UTC, levincent06 approved these changes

2021-02-07 00:41 UTC, AVSurfer123 approved these changes

2021-02-11 04:52 UTC, merged