[EXECUTOR] Changed log level in kill_subprocess()
pioneers/runtime pull request #211
Opened 2021-04-04 06:25 UTC by DanielMolina24

- Dependent on the signal that is received

2021-04-08 03:30 UTC, benliao1 approved these changes
Makes sense to me!

2021-04-09 00:49 UTC, AVSurfer123 reviewed
Why is the point of this? If its because the fix I told Ben to do with commenting out the `python_exit_handler`, then that isn't being included here. Otherwise, you will still want an unhandled SIGTERM to print this out.

2021-04-09 01:10 UTC, levincent06 commented
The issue is that because executor kills the subprocess with `SIGTERM`, it still prints out
```
Error when shutting down execution of mode <mode>
killed by signal 15
```
every single time the run mode changes from `AUTO`/`TELEOP` even though it's not really an error.

2021-04-10 20:50 UTC, AVSurfer123 commented
That shouldn't print out as there is a signal handler attached to SIGTERM. The only way it gets print out is if you comment/remove the signal handler, but that isn't part of this PR.

2021-04-10 22:14 UTC, AVSurfer123 requested changes

2021-04-10 22:14 UTC, AVSurfer123 commented on executor/executor.c
> +    log_printf((sig_number == DEBUG_SIGNAL) ? DEBUG : ERROR, "killed by signal %d\n", sig_number);
Instead of doing this, can you just put `exit(0)` at the beginning of `python_exit_handler`? and I guess comment the rest of the handler for now.

2021-04-10 22:14 UTC, AVSurfer123 commented on net_handler/net_handler.c
> +        read(connfd, &client_id, 1);
check for error on read

2021-04-15 04:06 UTC, AVSurfer123 commented on executor/executor.c
> +    log_printf((sig_number == DEBUG_SIGNAL) ? DEBUG : ERROR, "killed by signal %d\n", sig_number);
yea. but just comment out the other code in `python_exit_handler` for now.

2021-04-18 23:32 UTC, AVSurfer123 approved these changes

2021-04-19 02:37 UTC, merged